name=input('Enter your name:')
number=input('Enter your phone number:')
number=int(number)
age=input('Enter your age:')
age=int(age)
height=input('Enter your height:')
height=float(height)
Eircode=input('Enter your eircode:')
print('Your name is',name,', and your phone number is',number)
print('Your name is',name,', and your eircode is',Eircode)
print('Your age is',age,',and your height is',height)
print('Your name is',name,',your age is',age,',your height is',height,'and your eircode is',Eircode)